# Default values for overleaf-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#env: staging
env: develop
#env: production

develop:
#  mongoUrl: "mongodb://10.43.137.184:27017"
  mongoUrl: "mongodb://10.43.173.123:27017"
#  mongoUrl: "mongodb://mongo-service.overleaf-develop.svc.cluster.local:27017"
  redisHost: "redis-leader"
  sharelatexAppName: "Development Overleaf Instance"
  linkedFileTypes: "project_file,project_output_file"
  enableConversions: "true"
  emailConfirmationDisabled: "true"
  texmfvar: "/var/lib/sharelatex/tmp/texmf-var"
  getHostsFrom: "dns"
  mongoServicePort: 27017
  mongoServiceTargetPort: 27017
  mongoReplicas: 1
  mongoImage: "mongo:4.0"
  mongoMountPath: "/var/mongo-pvc-develop/mongo"
  mongoContainerPort: 27017
  redisServicePort: 6379
  redisServiceTargetPort: 6379
  redisReplicas: 1
  redisImage: "redis:5.0"
  redisMountPath: "/var/redis-pvc-develop/redis"
  redisCPU: "100m"
  redisMemory: "100Mi"
  redisContainerPort: 6379
  shareServicePort: 80
  shareReplicas: 1
#  shareImage: "sharelatex/sharelatex:2.7.0"
  shareImage: "mrobin23/overleaf:stable"
  shareMountPath: "/var/share-pvc-develop/share"
  shareContainerPort: 80
  shareIngressNumber: 80


staging:
  sample-key: sample-12345

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
