apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-develop
  labels:
    type: local
spec:
  storageClassName: database-develop
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/mongo-retain-develop"
