apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-develop
  labels:
    type: local
spec:
  storageClassName: redis-develop
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/redis-retain-develop"
