apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-pv-develop
  labels:
    type: local
spec:
  storageClassName: share-develop
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/share-retain-develop"
