apiVersion: v1
kind: Service
metadata:
  name: mongo
  {{if eq .Values.env "develop"}}
  namespace: overleaf-develop
  {{else if eq .Values.env "staging"}}
  namespace: overleaf-staging
  {{else}}
  namespace: overleaf
  {{end}}
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: {{.Values.develop.mongoServicePort}}
    targetPort: {{.Values.develop.mongoServiceTargetPort}}
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
