apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  {{if eq .Values.env "develop"}}
  namespace: overleaf-develop
  {{else if eq .Values.env "staging"}}
  namespace: overleaf-staging
  {{else}}
  namespace: overleaf
  {{end}}
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: {{.Values.develop.redisServicePort}}
    targetPort: {{.Values.develop.redisServiceTargetPort}}
  selector:
    app: redis
    role: leader
    tier: backend
