apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: share-ingress
  {{if eq .Values.env "develop"}}
  namespace: overleaf-develop
  {{else if eq .Values.env "staging"}}
  namespace: overleaf-staging
  {{else}}
  namespace: overleaf
  {{end}}
spec:
  tls:
  - hosts:
  {{if eq .Values.env "develop"}}
      - overleaf-develop.home
  {{else if eq .Values.env "staging"}}
      - overleaf-staging.home
  {{else}}
      - overleaf.home
  {{end}}
    secretName: secret-tls
  rules:
  {{if eq .Values.env "develop"}}
  - host: overleaf-develop.home
  {{else if eq .Values.env "staging"}}
  - host: overleaf-staging.home
  {{else}}
  - host: overleaf.home
  {{end}}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sharelatex
              port:
                number: {{.Values.develop.shareIngressNumber}}
