apiVersion: v1
kind: ConfigMap
metadata:
  name: share-configmap
  labels:
  {{if eq .Values.env "develop"}}
    app: sharelatex-develop
    namespace: overleaf-develop
  {{else if eq .Values.env "staging"}}
    app: sharelatex-staging
    namespace: overleaf-staging
  {{else}}
    app: sharelatex
  {{end}}
data:
  SHARELATEX_MONGO_URL: "{{.Values.develop.mongoUrl}}"
  SHARELATEX_REDIS_HOST: "{{.Values.develop.redisHost}}"
  REDIS_HOST: "{{.Values.develop.redisHost}}"
  SHARELATEX_APP_NAME: "{{.Values.develop.sharelatexAppName}}"
  ENABLED_LINKED_FILE_TYPES: "{{.Values.develop.linkedFileTypes}}"
  ENABLE_CONVERSIONS: "{{.Values.develop.enableConversions}}"
  EMAIL_CONFIRMATION_DISABLED: "{{.Values.develop.emailConfirmationDisabled}}"
  TEXMFVAR: "{{.Values.develop.texmfvar}}"
  GET_HOSTS_FROM: "{{.Values.develop.getHostsFrom}}"
